# Generated by Django 3.1.4 on 2023-10-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='created_by',
        ),
    ]
